#!/bin/sh
# rm2fb_uninstall_dev.sh — runs ON the reMarkable 2 (as root, via ssh).
#
# Removes exactly the files recorded in /opt/rm2fb/manifest (or the
# files.list fallback), touching nothing else. Files that have since been
# modified are kept and reported, not deleted.
#
# usage: sh rm2fb_uninstall_dev.sh
# Test hook: RM2FB_ROOT prefixes all device paths (sandbox testing only).

set -u

R="${RM2FB_ROOT:-}"

die() {
    echo "ERROR: $*" >&2
    exit 1
}

if [ -z "$R" ]; then
    [ "$(id -u)" = "0" ] || die "must run as root"
fi
command -v sha256sum >/dev/null 2>&1 || die "sha256sum not found; integrity checks require it"

file_hash() {
    sha256sum "$1" 2>/dev/null | cut -d' ' -f1
}

if [ "$(systemctl is-active rm2fb 2>/dev/null)" = "active" ]; then
    die "rm2fb service is running (a reader may be in progress); exit the reader first"
fi
systemctl stop rm2fb.service rm2fb.socket 2>/dev/null
systemctl reset-failed rm2fb.service 2>/dev/null

M="$R/opt/rm2fb/manifest"
LIST=""
if [ -f "$M" ]; then
    LIST="$(grep -E '^[FLD] ' "$M")"
elif [ -f "$R/opt/rm2fb/files.list" ]; then
    LIST="$(awk '$1 ~ /^[FL]$/ {print $1" "$2" "$4}' "$R/opt/rm2fb/files.list")"
else
    echo "No /opt/rm2fb/manifest or files.list found."
    echo "Nothing to remove — if you installed rm2fb by other means, remove it manually."
    exit 0
fi
[ -n "$LIST" ] || { echo "Manifest is empty — nothing to remove."; }

echo "-- removing"
REMOVED=0
KEPT=0
while read -r kind p check; do
    [ -n "${kind:-}" ] || continue
    t="$R/$p"
    case "$kind" in
        F)
            if [ -L "$t" ]; then
                KEPT=$((KEPT + 1))
                echo "  KEPT $p (is a symlink; expected regular file — check manually)"
            elif [ -e "$t" ]; then
                if [ "$(file_hash "$t")" = "$check" ]; then
                    rm -f "$t" && REMOVED=$((REMOVED + 1)) && echo "  removed $p"
                else
                    KEPT=$((KEPT + 1))
                    echo "  KEPT $p (content differs from installed copy)"
                fi
            fi
            ;;
        L)
            if [ -L "$t" ]; then
                if [ "$(readlink "$t")" = "$check" ]; then
                    rm "$t" && REMOVED=$((REMOVED + 1)) && echo "  removed $p (symlink)"
                else
                    KEPT=$((KEPT + 1))
                    echo "  KEPT $p (symlink target differs)"
                fi
            fi
            ;;
        D)
            if [ -d "$t" ] && [ -z "$(ls -A "$t" 2>/dev/null)" ]; then
                rmdir "$t" && echo "  removed dir $p"
            fi
            ;;
    esac
done <<EOF
$LIST
EOF

# generated reader launcher (covered by the manifest; this is a fallback
# for when only files.list survived)
if [ -f "$R/opt/rmx/xreader-rm2.sh" ] \
    && grep -q "Generated by rm2fb_install_dev.sh" "$R/opt/rmx/xreader-rm2.sh"; then
    rm -f "$R/opt/rmx/xreader-rm2.sh"
    REMOVED=$((REMOVED + 1))
    echo "  removed opt/rmx/xreader-rm2.sh"
fi

# manifest bookkeeping + dir cleanup
rm -f "$R/opt/rm2fb/manifest" "$R/opt/rm2fb/files.list"
rmdir "$R/opt/rm2fb" 2>/dev/null

systemctl daemon-reload 2>/dev/null

case "$(systemctl is-active xochitl 2>/dev/null)" in
    active) echo "xochitl (system UI): active" ;;
    *)
        systemctl start xochitl 2>/dev/null
        sleep 1
        case "$(systemctl is-active xochitl 2>/dev/null)" in
            active) echo "xochitl (system UI): restored" ;;
            *) echo "WARNING: xochitl not active — run: systemctl start xochitl" ;;
        esac
        ;;
esac

rm -rf "$R/tmp/rm2fb-stage" 2>/dev/null

echo
echo "Uninstall complete: $REMOVED removed, $KEPT kept (see list above)."
